'use client';

import { useQuery } from '@tanstack/react-query';
import Link from 'next/link';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { api, call } from '@/lib/api/client';
import { formatDateTime } from '@/lib/format';
import { useRequireAuth } from '@/lib/use-require-auth';

export default function TicketsPage() {
  const { status } = useRequireAuth();
  const { data: tickets } = useQuery({
    queryKey: ['tickets'],
    queryFn: () => call(api.GET('/api/v1/tickets')),
    enabled: status === 'authenticated',
  });

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-semibold">Vé của tôi</h1>
      {!tickets ? (
        <Skeleton className="h-64" />
      ) : tickets.length === 0 ? (
        <p className="text-muted-foreground">
          Bạn chưa có vé nào.{' '}
          <Link href="/" className="underline">
            Xem concert
          </Link>
        </p>
      ) : (
        <div className="grid gap-4 sm:grid-cols-2">
          {tickets.map((t) => {
            const state = t.voidedAt
              ? 'Đã vô hiệu'
              : t.checkedInAt
                ? 'Đã check-in'
                : null;
            return (
              <article
                key={t.id}
                data-testid="ticket"
                className={`flex gap-4 rounded-lg border p-4 ${state ? 'opacity-60' : ''}`}
              >
                {/* SVG generated by our own API from the random ticket code;
                    it contains no user input. */}
                <div
                  className="size-32 shrink-0 rounded bg-white p-1 [&_svg]:size-full"
                  aria-label={`Mã QR của vé ${t.code}`}
                  role="img"
                  dangerouslySetInnerHTML={{ __html: t.qrSvg }}
                />
                <div className="min-w-0 space-y-1 text-sm">
                  <div className="font-semibold">{t.concertName}</div>
                  <div className="text-muted-foreground">
                    {formatDateTime(t.startsAt)}
                    <br />
                    {t.venue}
                  </div>
                  <div>
                    {t.zoneName}
                    {t.seatLabel ? ` · ghế ${t.seatLabel}` : ' · vé đứng'}
                  </div>
                  <code className="block truncate text-xs text-muted-foreground">
                    {t.code}
                  </code>
                  {state && <Badge variant="secondary">{state}</Badge>}
                </div>
              </article>
            );
          })}
        </div>
      )}
    </div>
  );
}
