/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a customer account */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Returns an access token in the body and sets the refresh token as an
         *     httpOnly cookie, which page scripts cannot read (XSS cannot steal it).
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchanges the refresh cookie for a new access token and a new cookie */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revokes the refresh token (and its rotation family) and clears the cookie */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user's profile */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/concerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public catalog: concerts that have at least one published performance */
        get: operations["ConcertsController_list"];
        put?: never;
        post: operations["ConcertsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/concerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Concert with its published performances (the owner also sees drafts) */
        get: operations["ConcertsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/concerts/{id}/performances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a DRAFT performance with zones, a generated seat layout and sale phases */
        post: operations["ConcertsController_createPerformance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance detail: zones, prices and sale phases */
        get: operations["PerformancesController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["PerformancesController_update"];
        trace?: never;
    };
    "/api/v1/performances/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** DRAFT to PUBLISHED; the performance becomes visible to everyone */
        post: operations["PerformancesController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performances/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancels the performance: sales stop immediately; unpaid orders are
         *     cancelled and paid ones refunded in the background.
         */
        post: operations["PerformancesController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performances/{id}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every seat with its status, and remaining tickets per zone */
        get: operations["PerformancesController_seats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My orders, newest first */
        get: operations["OrdersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrdersController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Holds numbered seats and/or standing tickets and creates a PENDING order.
         *     Retrying with the same Idempotency-Key returns the same order (with the
         *     header Idempotent-Replayed: true) instead of holding more tickets.
         */
        post: operations["ReservationsController_reserve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancels my PENDING order and releases its tickets immediately */
        post: operations["OrderCancellationController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts paying for my PENDING order; returns the gateway URL */
        post: operations["OrderPaymentController_pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/ipn/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Instant Payment Notification, called by the gateway (VNPay uses GET).
         *     Authenticated by its HMAC-SHA512 signature, not by a token. Always
         *     answers 200 with a VNPay RspCode.
         */
        get: operations["PaymentsController_ipn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/return/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Where the gateway sends the browser back. Display only: changes nothing */
        get: operations["PaymentsController_returnUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/fake/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fake gateway (dev and tests only): the payment page, as data */
        get: operations["PaymentsController_fakeCheckout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/fake/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fake gateway (dev and tests only): pay or give up, then the IPN is sent */
        post: operations["PaymentsController_fakeComplete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My tickets with their QR codes */
        get: operations["TicketsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scans a ticket at the gate; each ticket is accepted exactly once */
        post: operations["TicketsController_checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /**
             * Format: email
             * @example jane@example.com
             */
            email: string;
            password: string;
            /** @example Jane Doe */
            fullName: string;
        };
        UserResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example jane@example.com */
            email: string;
            /** @example Jane Doe */
            fullName: string;
            /** @enum {string} */
            role: "CUSTOMER" | "ORGANIZER" | "STAFF";
        };
        LoginDto: {
            /**
             * Format: email
             * @example jane@example.com
             */
            email: string;
            password: string;
        };
        AuthResponseDto: {
            /** @description JWT to send as "Authorization: Bearer <token>" */
            accessToken: string;
            /**
             * @description Access token lifetime in seconds
             * @example 900
             */
            expiresIn: number;
            user: components["schemas"]["UserResponseDto"];
        };
        PerformanceSummaryDto: {
            /** Format: uuid */
            id: string;
            venue: string;
            /** Format: date-time */
            startsAt: string;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED";
        };
        ConcertResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            artist: string;
            description: string;
            performances: components["schemas"]["PerformanceSummaryDto"][];
        };
        ConcertPageDto: {
            items: components["schemas"]["ConcertResponseDto"][];
            page: number;
            pageSize: number;
            total: number;
        };
        CreateConcertDto: {
            /** @example Questa Fest 2026 */
            name: string;
            /** @example The Questa Band */
            artist: string;
            description?: string;
        };
        CreateZoneDto: {
            /** @example VIP */
            name: string;
            /** @enum {string} */
            type: "SEATED" | "STANDING";
            /**
             * @description Ticket price in VND
             * @example 3000000
             */
            price: number;
            /** @description SEATED only: number of rows */
            rows?: number;
            /** @description SEATED only: seats in each row */
            seatsPerRow?: number;
            /** @description STANDING only: ticket count */
            capacity?: number;
        };
        CreateSalePhaseDto: {
            /** @enum {string} */
            type: "PRESALE" | "GENERAL";
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
        };
        CreatePerformanceDto: {
            /** @example My Dinh National Stadium */
            venue: string;
            /** Format: date-time */
            startsAt: string;
            /** @default 6 */
            maxTicketsPerUser: number;
            zones: components["schemas"]["CreateZoneDto"][];
            salePhases: components["schemas"]["CreateSalePhaseDto"][];
        };
        ConcertRefDto: {
            /** Format: uuid */
            id: string;
            name: string;
            artist: string;
        };
        ZoneResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            type: "SEATED" | "STANDING";
            /** @description VND */
            price: number;
            capacity: number;
        };
        SalePhaseResponseDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "PRESALE" | "GENERAL";
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
        };
        PerformanceResponseDto: {
            /** Format: uuid */
            id: string;
            concert: components["schemas"]["ConcertRefDto"];
            venue: string;
            /** Format: date-time */
            startsAt: string;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED";
            maxTicketsPerUser: number;
            zones: components["schemas"]["ZoneResponseDto"][];
            salePhases: components["schemas"]["SalePhaseResponseDto"][];
        };
        UpdatePerformanceDto: {
            /** @example My Dinh National Stadium */
            venue?: string;
            /** Format: date-time */
            startsAt?: string;
            /** @default 6 */
            maxTicketsPerUser: number;
        };
        ZoneAvailabilityDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            type: "SEATED" | "STANDING";
            /** @description VND */
            price: number;
            capacity: number;
            /** @description Tickets that can still be held right now */
            available: number;
        };
        SeatResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            zoneId: string;
            /** @example A */
            row: string;
            /** @example 1 */
            number: number;
            /** @enum {string} */
            status: "AVAILABLE" | "HELD" | "SOLD";
        };
        SeatMapResponseDto: {
            /** Format: uuid */
            performanceId: string;
            zones: components["schemas"]["ZoneAvailabilityDto"][];
            seats: components["schemas"]["SeatResponseDto"][];
        };
        OrderItemResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            zoneId: string;
            /** Format: uuid */
            seatId: string | null;
            /** @description VND */
            price: number;
        };
        OrderResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            performanceId: string;
            /** @enum {string} */
            status: "PENDING" | "PAID" | "EXPIRED" | "CANCELLED" | "REFUND_PENDING" | "REFUNDED";
            /** @description VND */
            totalAmount: number;
            /**
             * Format: date-time
             * @description The hold ends at this time unless the order is paid
             */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            items: components["schemas"]["OrderItemResponseDto"][];
        };
        StandingSelectionDto: {
            /** Format: uuid */
            zoneId: string;
            quantity: number;
        };
        CreateReservationDto: {
            /** Format: uuid */
            performanceId: string;
            /** @description Numbered seats to hold */
            seatIds?: string[];
            /** @description Standing tickets per zone */
            standing?: components["schemas"]["StandingSelectionDto"][];
        };
        PayOrderDto: {
            /**
             * @description Defaults to PAYMENT_PROVIDER
             * @enum {string}
             */
            provider?: "vnpay" | "fake";
        };
        CheckoutResponseDto: {
            /** Format: uuid */
            paymentId: string;
            /** @enum {string} */
            provider: "vnpay" | "fake";
            /** @description Send the customer's browser here to pay */
            checkoutUrl: string;
            /**
             * Format: date-time
             * @description The gateway refuses payment after this time
             */
            expiresAt: string;
        };
        IpnResponseDto: {
            /** @description 00 confirmed, 01 order not found, 02 already confirmed, 04 invalid amount, 97 invalid signature, 99 unknown error */
            RspCode: string;
            Message: string;
        };
        PaymentReturnResponseDto: {
            /** @description The signature of the redirect is valid */
            verified: boolean;
            /** @description What the redirect claims; the order changes only through the IPN */
            gatewaySaysSuccess: boolean;
            responseCode: string | null;
            /** Format: uuid */
            orderId: string | null;
            /** @enum {string|null} */
            orderStatus: "PENDING" | "PAID" | "EXPIRED" | "CANCELLED" | "REFUND_PENDING" | "REFUNDED" | null;
            /** @enum {string|null} */
            paymentStatus: "PENDING" | "SUCCEEDED" | "FAILED" | null;
        };
        FakeCheckoutResponseDto: {
            txnRef: string;
            /** @description VND */
            amount: number;
            /** Format: uuid */
            orderId: string;
            /** @enum {string} */
            paymentStatus: "PENDING" | "SUCCEEDED" | "FAILED";
            outcomes: ("success" | "cancelled" | "failed")[];
        };
        FakeCompleteDto: {
            txnRef: string;
            /** @enum {string} */
            outcome: "success" | "cancelled" | "failed";
            /** @description Amount the gateway reports (VND); defaults to the right one */
            amount?: number;
        };
        FakeCompleteResponseDto: {
            /** @description What our IPN answered */
            ipn: components["schemas"]["IpnResponseDto"];
            /** @description How many times the gateway delivered the IPN (retries on 99) */
            deliveries: number;
            /** @description Where the gateway sends the browser back */
            returnUrl: string;
        };
        TicketResponseDto: {
            /** Format: uuid */
            id: string;
            /** @description What the QR code encodes; shown at the gate */
            code: string;
            /** @description QR code of `code`, as an SVG document */
            qrSvg: string;
            /** Format: uuid */
            orderId: string;
            /** Format: uuid */
            performanceId: string;
            concertName: string;
            venue: string;
            /** Format: date-time */
            startsAt: string;
            zoneName: string;
            /** @description Row and number, e.g. "B12"; null in a standing zone */
            seatLabel: string | null;
            /** Format: date-time */
            issuedAt: string;
            /** Format: date-time */
            checkedInAt: string | null;
            /**
             * Format: date-time
             * @description Set when the order left PAID; the ticket is no longer valid
             */
            voidedAt: string | null;
        };
        CheckInDto: {
            /** @description The code read from the QR */
            code: string;
        };
        CheckInResponseDto: {
            /** Format: uuid */
            ticketId: string;
            /** Format: date-time */
            checkedInAt: string;
            zoneName: string;
            seatLabel: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    ConcertsController_list: {
        parameters: {
            query: {
                /** @description Page number, starting at 1 */
                page: number;
                /** @description Items per page */
                pageSize: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConcertPageDto"];
                };
            };
        };
    };
    ConcertsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConcertDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConcertResponseDto"];
                };
            };
        };
    };
    ConcertsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConcertResponseDto"];
                };
            };
        };
    };
    ConcertsController_createPerformance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePerformanceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceResponseDto"];
                };
            };
        };
    };
    PerformancesController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceResponseDto"];
                };
            };
        };
    };
    PerformancesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePerformanceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceResponseDto"];
                };
            };
        };
    };
    PerformancesController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceResponseDto"];
                };
            };
        };
    };
    PerformancesController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceResponseDto"];
                };
            };
        };
    };
    PerformancesController_seats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatMapResponseDto"];
                };
            };
        };
    };
    OrdersController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"][];
                };
            };
        };
    };
    OrdersController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
        };
    };
    ReservationsController_reserve: {
        parameters: {
            query?: never;
            header: {
                /** @description Unique per purchase attempt (e.g. a UUID), 1-100 characters of A-Z a-z 0-9 _ . : - */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReservationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
        };
    };
    OrderCancellationController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderPaymentController_pay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponseDto"];
                };
            };
        };
    };
    PaymentsController_ipn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IpnResponseDto"];
                };
            };
        };
    };
    PaymentsController_returnUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentReturnResponseDto"];
                };
            };
        };
    };
    PaymentsController_fakeCheckout: {
        parameters: {
            query: {
                txnRef: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FakeCheckoutResponseDto"];
                };
            };
        };
    };
    PaymentsController_fakeComplete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FakeCompleteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FakeCompleteResponseDto"];
                };
            };
        };
    };
    TicketsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponseDto"][];
                };
            };
        };
    };
    TicketsController_checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInResponseDto"];
                };
            };
        };
    };
}
